package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "NoiseAnalysis",
    srcs = [],
    hdrs = [
        "NoiseAnalysis.h",
    ],
    deps = [
        "@heir//lib/Analysis/SecretnessAnalysis",
        "@llvm-project//mlir:Analysis",
        "@llvm-project//mlir:CallOpInterfaces",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:Support",
    ],
)
