# Polynomial approximations of transcendental functions

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "Sign",
    hdrs = ["Sign.h"],
)
