#include <cstdint>
#include <cstdlib>
#include <vector>

#include "gtest/gtest.h"  // from @googletest
#include "tests/llvm_runner/memref_types.h"

#if defined(__has_feature)
#if __has_feature(memory_sanitizer)
#include <sanitizer/msan_interface.h>
#define HEIR_MSAN_UNPOISON(p, s) __msan_unpoison((p), (s))
#else
#define HEIR_MSAN_UNPOISON(p, s)
#endif
#else
#define HEIR_MSAN_UNPOISON(p, s)
#endif

// Generated by the Rotom pipeline: every public input -- both weight matrices
// and both biases -- is packed at its assigned layout by
// __packed_plaintext__argN, the secret image is encrypted by __encrypt__arg4,
// and the result is decrypted by __decrypt__result0. Packed values are rows of
// ciphertext-sized slots, so every argument of the entry point is rank 2.
extern "C" {
void _mlir_ciface_mnist(StridedMemRefType<float, 2>* res,
                        StridedMemRefType<float, 2>* w1,
                        StridedMemRefType<float, 2>* b1,
                        StridedMemRefType<float, 2>* w2,
                        StridedMemRefType<float, 2>* b2,
                        StridedMemRefType<float, 2>* x);
void _mlir_ciface_mnist__packed_plaintext__arg0(
    StridedMemRefType<float, 2>* res, StridedMemRefType<float, 2>* arg);
void _mlir_ciface_mnist__packed_plaintext__arg1(
    StridedMemRefType<float, 2>* res, StridedMemRefType<float, 1>* arg);
void _mlir_ciface_mnist__packed_plaintext__arg2(
    StridedMemRefType<float, 2>* res, StridedMemRefType<float, 2>* arg);
void _mlir_ciface_mnist__packed_plaintext__arg3(
    StridedMemRefType<float, 2>* res, StridedMemRefType<float, 1>* arg);
void _mlir_ciface_mnist__encrypt__arg4(StridedMemRefType<float, 2>* res,
                                       StridedMemRefType<float, 2>* arg);
void _mlir_ciface_mnist__decrypt__result0(StridedMemRefType<float, 2>* res,
                                          StridedMemRefType<float, 2>* arg);
}

namespace {

constexpr int64_t kIn = 784, kHidden = 512, kOut = 10;

StridedMemRefType<float, 2> memref2(std::vector<float>& data, int64_t rows,
                                    int64_t cols) {
  int64_t sizes[2] = {rows, cols};
  int64_t strides[2] = {cols, 1};
  return StridedMemRefType<float, 2>(data.data(), data.data(), 0, sizes,
                                     strides);
}
StridedMemRefType<float, 1> memref1(std::vector<float>& data, int64_t n) {
  int64_t sizes[1] = {n};
  int64_t strides[1] = {1};
  return StridedMemRefType<float, 1>(data.data(), data.data(), 0, sizes,
                                     strides);
}

}  // namespace

TEST(MnistRotomPlaintextTest, MatchesReference) {
  std::vector<float> w1(kHidden * kIn), b1(kHidden), w2(kOut * kHidden),
      b2(kOut), x(kIn);
  for (int64_t i = 0; i < kHidden; ++i) {
    for (int64_t k = 0; k < kIn; ++k) {
      w1[i * kIn + k] = static_cast<float>((i + 2 * k) % 5 - 2) / 100.0f;
    }
    b1[i] = static_cast<float>(i % 7 - 3) / 10.0f;
  }
  for (int64_t j = 0; j < kOut; ++j) {
    for (int64_t i = 0; i < kHidden; ++i) {
      w2[j * kHidden + i] = static_cast<float>((3 * i + j) % 5 - 2) / 100.0f;
    }
    b2[j] = static_cast<float>(j % 3 - 1) / 10.0f;
  }
  for (int64_t k = 0; k < kIn; ++k) {
    x[k] = static_cast<float>((k * 7) % 16) / 100.0f;
  }

  std::vector<float> relu(kHidden);
  for (int64_t i = 0; i < kHidden; ++i) {
    float h = b1[i];
    for (int64_t k = 0; k < kIn; ++k) h += w1[i * kIn + k] * x[k];
    float t = h * 0.05f;
    float u = t * 10.0f + 6.33939934f;
    float v = t * t * 2.0f - 1.0f;
    float w = u + v * 4.30750513f;
    float z = v * v * 2.0f - 1.0f;
    relu[i] = w + z * -1.26569366f;
  }
  std::vector<float> expected(kOut);
  for (int64_t j = 0; j < kOut; ++j) {
    float o = b2[j];
    for (int64_t i = 0; i < kHidden; ++i) o += w2[j * kHidden + i] * relu[i];
    expected[j] = o;
  }

  auto w1Ref = memref2(w1, kHidden, kIn);
  auto b1Ref = memref1(b1, kHidden);
  auto w2Ref = memref2(w2, kOut, kHidden);
  auto b2Ref = memref1(b2, kOut);
  auto xRef = memref2(x, 1, kIn);

  StridedMemRefType<float, 2> w1Packed, b1Packed, w2Packed, b2Packed, xEnc,
      resPacked, out;
  _mlir_ciface_mnist__packed_plaintext__arg0(&w1Packed, &w1Ref);
  HEIR_MSAN_UNPOISON(&w1Packed, sizeof(w1Packed));
  _mlir_ciface_mnist__packed_plaintext__arg1(&b1Packed, &b1Ref);
  HEIR_MSAN_UNPOISON(&b1Packed, sizeof(b1Packed));
  _mlir_ciface_mnist__packed_plaintext__arg2(&w2Packed, &w2Ref);
  HEIR_MSAN_UNPOISON(&w2Packed, sizeof(w2Packed));
  _mlir_ciface_mnist__packed_plaintext__arg3(&b2Packed, &b2Ref);
  HEIR_MSAN_UNPOISON(&b2Packed, sizeof(b2Packed));
  _mlir_ciface_mnist__encrypt__arg4(&xEnc, &xRef);
  HEIR_MSAN_UNPOISON(&xEnc, sizeof(xEnc));
  _mlir_ciface_mnist(&resPacked, &w1Packed, &b1Packed, &w2Packed, &b2Packed,
                     &xEnc);
  HEIR_MSAN_UNPOISON(&resPacked, sizeof(resPacked));
  _mlir_ciface_mnist__decrypt__result0(&out, &resPacked);
  HEIR_MSAN_UNPOISON(&out, sizeof(out));
  HEIR_MSAN_UNPOISON(out.basePtr, kOut * sizeof(float));

  for (int64_t j = 0; j < kOut; ++j) {
    float actual = out.data[0 * out.strides[0] + j * out.strides[1]];
    EXPECT_NEAR(expected[j], actual, 1e-2) << "mismatch at output " << j;
  }
  free(w1Packed.basePtr);
  free(w2Packed.basePtr);
  free(xEnc.basePtr);
  free(resPacked.basePtr);
  free(out.basePtr);
}
