# Test utilities related to Verilog

load("//third_party/bazel_rules/rules_python/python:py_binary.bzl", "py_binary")

py_binary(
    name = "run_verilog",
    srcs = [
        "run_verilog.py",
    ],
    python_version = "PY3",
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [],
)
