# Test utilities related to Verilog

py_binary(
    name = "run_verilog",
    srcs = [
        "run_verilog.py",
    ],
    python_version = "PY3",
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [],
)
