load("//learning/grp/pynball:build_defs.bzl", "ipynb_deps")

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

ipynb_deps(
    name = "heir__play_deps",
    srcs = ["HEIR Play.ipynb"],
    pytype = False,
)
