// RUN: heir-opt %s --split-input-file --convert-to-ciphertext-semantics=ciphertext-size=32 | FileCheck %s


// Test that a vector of size 16xi16 is replicated to 1x32xi16.

// CHECK: func.func @repeat_vector_nonconst
#layout = #tensor_ext.layout<"{ [i0] -> [ct, slot] : ct = 0 and (-i0 + slot) mod 16 = 0 and 0 <= i0 <= 15 and 0 <= slot <= 31 }">
module {
  func.func @repeat_vector_nonconst() {
    %cst = arith.constant dense<[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]> : tensor<16xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<{{\[\[}}0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15{{\]\]}}> : tensor<1x32xi16>
    // CHECK: return
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout, tensor_ext.layout = #layout} : tensor<16xi16>
      secret.yield %1 : tensor<16xi16>
    } -> (!secret.secret<tensor<16xi16>> {tensor_ext.layout = #layout})
    return
  }
}

// -----

// Checks that a dense constant vector of size 16xi16 is replaced with a dense
// constant of size 1x32xi16.
// CHECK: @repeat_vector
#layout = #tensor_ext.layout<"{ [i0] -> [ct, slot] : ct = 0 and (-i0 + slot) mod 16 = 0 and 0 <= i0 <= 15 and 0 <= slot <= 31 }">
module {
  func.func @repeat_vector() {
    %cst = arith.constant dense<1> : tensor<16xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<1> : tensor<1x32xi16>
    // CHECK: secret.yield %[[cst]] : tensor<1x32xi16>
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout, tensor_ext.layout = #layout} : tensor<16xi16>
      secret.yield %1 : tensor<16xi16>
    } -> (!secret.secret<tensor<16xi16>> {tensor_ext.layout = #layout})
    return
  }
}

// -----

#layout = #tensor_ext.layout<"{ [] -> [ct, slot] : ct = 0 and 0 <= slot <= 31 }">
module {
  // CHECK: @scalar_mul
  func.func @scalar_mul(%arg0: !secret.secret<i16> {tensor_ext.layout = #layout}) -> (!secret.secret<i16> {tensor_ext.layout = #layout}) {
    // Dropping unit dims results in a 32xi16 tensor for assign layout
    // CHECK: %[[cst:.*]] = arith.constant dense<2> : tensor<1x32xi16>
    %0 = secret.generic(%arg0: !secret.secret<i16> {tensor_ext.layout = #layout}) {
    ^body(%input0: i16):
      %c2_i16 = arith.constant 2 : i16
      %1 = tensor_ext.assign_layout %c2_i16 {layout = #layout, tensor_ext.layout = #layout} : i16
      %2 = arith.muli %input0, %1 {tensor_ext.layout = #layout} : i16
      secret.yield %2 : i16
    } -> (!secret.secret<i16> {tensor_ext.layout = #layout})
    // CHECK: return {{.*}} : !secret.secret<tensor<1x32xi16>>
    return %0 : !secret.secret<i16>
  }
}

// -----

#layout = #tensor_ext.layout<"{ [i0] -> [ct, slot] : ct = 0 and (-i0 + slot) mod 16 = 0 and 0 <= i0 <= 15 and 0 <= slot <= 31 }">
module {
  // CHECK: @empty
  func.func @empty() -> (!secret.secret<tensor<32xi16>> {tensor_ext.layout = #layout}) {
    %0 = secret.generic() {
      // CHECK: %[[empty:.*]] = tensor.empty() : tensor<1x32xi16>
      %empty = tensor.empty() : tensor<32xi16>
      %1 = tensor_ext.assign_layout %empty {layout = #layout, tensor_ext.layout = #layout} : tensor<32xi16>
      secret.yield %1 : tensor<32xi16>
    } -> (!secret.secret<tensor<32xi16>> {tensor_ext.layout = #layout})
    // CHECK: secret.yield %[[empty]] : tensor<1x32xi16>
    // CHECK: return {{.*}} : !secret.secret<tensor<1x32xi16>>
    return %0 : !secret.secret<tensor<32xi16>>
  }
}

// -----

// CHECK: func.func private @_assign_layout_{{[0-9]+}}
// CHECK-SAME: %[[ARG0:.*]]: tensor<1x32xi16>) -> tensor<1x32xi16>
// CHECK-DAG: %[[c4:.*]] = arith.constant 4 : index
// CHECK-DAG: %[[c3:.*]] = arith.constant 3 : index
// CHECK-DAG: %[[c5:.*]] = arith.constant 5 : index
// CHECK-DAG: %[[c2:.*]] = arith.constant 2 : index
// CHECK-DAG: %[[c6:.*]] = arith.constant 6 : index
// CHECK-DAG: %[[c1:.*]] = arith.constant 1 : index
// CHECK-DAG: %[[c7:.*]] = arith.constant 7 : index
// CHECK-DAG: %[[cst:.*]] = arith.constant dense<0> : tensor<1x32xi16>
// CHECK-DAG: %[[c0:.*]] = arith.constant 0 : index
// CHECK-DAG: %[[EXT0:.*]] = tensor.extract %arg0[%[[c0]], %[[c0]]]
// CHECK-DAG: %[[INS0:.*]] = tensor.insert %[[EXT0]] into %[[cst]][%[[c0]], %[[c7]]]
// CHECK-DAG: %[[EXT1:.*]] = tensor.extract %arg0[%[[c0]], %[[c1]]]
// CHECK-DAG: %[[INS1:.*]] = tensor.insert %[[EXT1]] into %[[INS0]][%[[c0]], %[[c6]]]
// CHECK-DAG: %[[EXT2:.*]] = tensor.extract %arg0[%[[c0]], %[[c2]]]
// CHECK-DAG: %[[INS2:.*]] = tensor.insert %[[EXT2]] into %[[INS1]][%[[c0]], %[[c5]]]
// CHECK-DAG: %[[EXT3:.*]] = tensor.extract %arg0[%[[c0]], %[[c3]]]
// CHECK-DAG: %[[INS3:.*]] = tensor.insert %[[EXT3]] into %[[INS2]][%[[c0]], %[[c4]]]
// CHECK-DAG: %[[EXT4:.*]] = tensor.extract %arg0[%[[c0]], %[[c4]]]
// CHECK-DAG: %[[INS4:.*]] = tensor.insert %[[EXT4]] into %[[INS3]][%[[c0]], %[[c3]]]
// CHECK-DAG: %[[EXT5:.*]] = tensor.extract %arg0[%[[c0]], %[[c5]]]
// CHECK-DAG: %[[INS5:.*]] = tensor.insert %[[EXT5]] into %[[INS4]][%[[c0]], %[[c2]]]
// CHECK-DAG: %[[EXT6:.*]] = tensor.extract %arg0[%[[c0]], %[[c6]]]
// CHECK-DAG: %[[INS6:.*]] = tensor.insert %[[EXT6]] into %[[INS5]][%[[c0]], %[[c1]]]
// CHECK-DAG: %[[EXT7:.*]] = tensor.extract %arg0[%[[c0]], %[[c7]]]
// CHECK-DAG: %[[INS7:.*]] = tensor.insert %[[EXT7]] into %[[INS6]][%[[c0]], %[[c0]]]

// CHECK: @permutate_vector
#layout = dense<[[0, 0, 0, 7], [0, 1, 0, 6], [0, 2, 0, 5], [0, 3, 0, 4], [0, 4, 0, 3], [0, 5, 0, 2], [0, 6, 0, 1], [0, 7, 0, 0]]> : tensor<8x4xi64>
module {
  func.func @permutate_vector() {
    %cst = arith.constant dense<1> : tensor<1x32xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<1> : tensor<1x32xi16>
    // CHECK: func.call @_assign_layout_{{[0-9]+}}(%[[cst]])
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout, tensor_ext.layout = #layout} : tensor<1x32xi16>
      secret.yield %1 : tensor<1x32xi16>
    } -> (!secret.secret<tensor<1x32xi16>> {tensor_ext.layout = #layout})
    return
  }
}

// -----

// CHECK: func.func private @_assign_layout_{{[0-9]+}}(%arg0: tensor<16xi16>) -> tensor<1x32xi16>
// CHECK-DAG: %[[C0:.*]] = arith.constant 0 : index
// CHECK-DAG: %[[C1:.*]] = arith.constant 1 : index
// CHECK-DAG: %[[C2:.*]] = arith.constant 2 : index
// CHECK-DAG: %[[C3:.*]] = arith.constant 3 : index
// CHECK-DAG: %[[C4:.*]] = arith.constant 4 : index
// CHECK-DAG: %[[C5:.*]] = arith.constant 5 : index
// CHECK-DAG: %[[C6:.*]] = arith.constant 6 : index
// CHECK-DAG: %[[C7:.*]] = arith.constant 7 : index
// CHECK-DAG: %[[C9:.*]] = arith.constant 9 : index
// CHECK-DAG: %[[ZERO:.*]] = arith.constant dense<0> : tensor<1x32xi16>
// CHECK-DAG: %[[E0:.*]] = tensor.extract %arg0[%[[C0]]] : tensor<16xi16>
// CHECK-DAG: %[[I0:.*]] = tensor.insert %[[E0]] into %[[ZERO]][%[[C0]], %[[C7]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E1:.*]] = tensor.extract %arg0[%[[C1]]] : tensor<16xi16>
// CHECK-DAG: %[[I1:.*]] = tensor.insert %[[E1]] into %[[I0]][%[[C0]], %[[C9]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E2:.*]] = tensor.extract %arg0[%[[C2]]] : tensor<16xi16>
// CHECK-DAG: %[[I2:.*]] = tensor.insert %[[E2]] into %[[I1]][%[[C0]], %[[C5]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E3:.*]] = tensor.extract %arg0[%[[C3]]] : tensor<16xi16>
// CHECK-DAG: %[[I3:.*]] = tensor.insert %[[E3]] into %[[I2]][%[[C0]], %[[C4]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E4:.*]] = tensor.extract %arg0[%[[C4]]] : tensor<16xi16>
// CHECK-DAG: %[[I4:.*]] = tensor.insert %[[E4]] into %[[I3]][%[[C0]], %[[C3]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E5:.*]] = tensor.extract %arg0[%[[C5]]] : tensor<16xi16>
// CHECK-DAG: %[[I5:.*]] = tensor.insert %[[E5]] into %[[I4]][%[[C0]], %[[C2]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E6:.*]] = tensor.extract %arg0[%[[C6]]] : tensor<16xi16>
// CHECK-DAG: %[[I6:.*]] = tensor.insert %[[E6]] into %[[I5]][%[[C0]], %[[C1]]] : tensor<1x32xi16>
// CHECK-DAG: %[[E7:.*]] = tensor.extract %arg0[%[[C7]]] : tensor<16xi16>
// CHECK-DAG: %[[I7:.*]] = tensor.insert %[[E7]] into %[[I6]][%[[C0]], %[[C0]]] : tensor<1x32xi16>
// CHECK-DAG: return %[[I7]] : tensor<1x32xi16>

// CHECK: @permutate_vector_other
#layout2 = dense<[[0, 0, 0, 7], [0, 1, 0, 9], [0, 2, 0, 5], [0, 3, 0, 4], [0, 4, 0, 3], [0, 5, 0, 2], [0, 6, 0, 1], [0, 7, 0, 0]]> : tensor<8x4xi64>
module {
  func.func @permutate_vector_other() {
    %cst = arith.constant dense<1> : tensor<16xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<1> : tensor<16xi16>
    // CHECK: func.call @_assign_layout_{{[0-9]+}}(%[[cst]])
    // CHECK: return
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout2, tensor_ext.layout = #layout2} : tensor<16xi16>
      secret.yield %1 : tensor<16xi16>
    } -> (!secret.secret<tensor<16xi16>> {tensor_ext.layout = #layout2})
    return
  }
}

// -----

// Test that a tensor<2x8xi16> input preserves its leading ct dim when emitted
// into a ciphertext-semantic tensor<2x32xi16>, and that permutation entries
// can stay within their own ciphertext.

// CHECK: func.func private @_assign_layout_{{[0-9]+}}
// CHECK-SAME: %[[ARG0:.*]]: tensor<2x8xi16>) -> tensor<2x32xi16>
// CHECK-DAG: %[[C0:.*]] = arith.constant 0 : index
// CHECK-DAG: %[[C1:.*]] = arith.constant 1 : index
// CHECK-DAG: %[[C2:.*]] = arith.constant 2 : index
// CHECK-DAG: %[[C5:.*]] = arith.constant 5 : index
// CHECK-DAG: %[[C7:.*]] = arith.constant 7 : index
// CHECK-DAG: %[[C10:.*]] = arith.constant 10 : index
// CHECK-DAG: %[[ZERO:.*]] = arith.constant dense<0> : tensor<2x32xi16>
// CHECK-DAG: %[[E0:.*]] = tensor.extract %arg0[%[[C0]], %[[C0]]] : tensor<2x8xi16>
// CHECK-DAG: %[[I0:.*]] = tensor.insert %[[E0]] into %[[ZERO]][%[[C0]], %[[C7]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E1:.*]] = tensor.extract %arg0[%[[C0]], %[[C2]]] : tensor<2x8xi16>
// CHECK-DAG: %[[I1:.*]] = tensor.insert %[[E1]] into %[[I0]][%[[C0]], %[[C10]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E2:.*]] = tensor.extract %arg0[%[[C1]], %[[C1]]] : tensor<2x8xi16>
// CHECK-DAG: %[[I2:.*]] = tensor.insert %[[E2]] into %[[I1]][%[[C1]], %[[C5]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E3:.*]] = tensor.extract %arg0[%[[C1]], %[[C5]]] : tensor<2x8xi16>
// CHECK-DAG: %[[I3:.*]] = tensor.insert %[[E3]] into %[[I2]][%[[C1]], %[[C0]]] : tensor<2x32xi16>
// CHECK: return %[[I3]] : tensor<2x32xi16>

// CHECK: @permutate_within_ct
#layout_within = dense<[
  [0, 0, 0, 7],
  [0, 2, 0, 10],
  [1, 1, 1, 5],
  [1, 5, 1, 0]
]> : tensor<4x4xi64>
module {
  func.func @permutate_within_ct() {
    %cst = arith.constant dense<1> : tensor<2x8xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<1> : tensor<2x8xi16>
    // CHECK: func.call @_assign_layout_{{[0-9]+}}(%[[cst]])
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout_within, tensor_ext.layout = #layout_within} : tensor<2x8xi16>
      secret.yield %1 : tensor<2x8xi16>
    } -> (!secret.secret<tensor<2x8xi16>> {tensor_ext.layout = #layout_within})
    return
  }
}

// -----

// Test that a multi-ciphertext input can have data moved BETWEEN ciphertexts:
// some src_ct=0 entries go to dst_ct=1 and vice versa.

// CHECK: func.func private @_assign_layout_{{[0-9]+}}
// CHECK-SAME: %[[ARG0:.*]]: tensor<2x16xi16>) -> tensor<2x32xi16>
// CHECK-DAG: %[[C0:.*]] = arith.constant 0 : index
// CHECK-DAG: %[[C1:.*]] = arith.constant 1 : index
// CHECK-DAG: %[[C3:.*]] = arith.constant 3 : index
// CHECK-DAG: %[[C4:.*]] = arith.constant 4 : index
// CHECK-DAG: %[[C5:.*]] = arith.constant 5 : index
// CHECK-DAG: %[[C7:.*]] = arith.constant 7 : index
// CHECK-DAG: %[[ZERO:.*]] = arith.constant dense<0> : tensor<2x32xi16>
// CHECK-DAG: %[[E0:.*]] = tensor.extract %arg0[%[[C0]], %[[C0]]] : tensor<2x16xi16>
// CHECK-DAG: %[[I0:.*]] = tensor.insert %[[E0]] into %[[ZERO]][%[[C1]], %[[C5]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E1:.*]] = tensor.extract %arg0[%[[C0]], %[[C3]]] : tensor<2x16xi16>
// CHECK-DAG: %[[I1:.*]] = tensor.insert %[[E1]] into %[[I0]][%[[C0]], %[[C7]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E2:.*]] = tensor.extract %arg0[%[[C1]], %[[C0]]] : tensor<2x16xi16>
// CHECK-DAG: %[[I2:.*]] = tensor.insert %[[E2]] into %[[I1]][%[[C0]], %[[C4]]] : tensor<2x32xi16>
// CHECK-DAG: %[[E3:.*]] = tensor.extract %arg0[%[[C1]], %[[C7]]] : tensor<2x16xi16>
// CHECK-DAG: %[[I3:.*]] = tensor.insert %[[E3]] into %[[I2]][%[[C1]], %[[C0]]] : tensor<2x32xi16>
// CHECK: return %[[I3]] : tensor<2x32xi16>

// CHECK: @permutate_cross_ct
#layout_cross = dense<[
  [0, 0, 1, 5],
  [0, 3, 0, 7],
  [1, 0, 0, 4],
  [1, 7, 1, 0]
]> : tensor<4x4xi64>
module {
  func.func @permutate_cross_ct() {
    %cst = arith.constant dense<1> : tensor<2x16xi16>
    // CHECK: %[[cst:.*]] = arith.constant dense<1> : tensor<2x16xi16>
    // CHECK: func.call @_assign_layout_{{[0-9]+}}(%[[cst]])
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout_cross, tensor_ext.layout = #layout_cross} : tensor<2x16xi16>
      secret.yield %1 : tensor<2x16xi16>
    } -> (!secret.secret<tensor<2x16xi16>> {tensor_ext.layout = #layout_cross})
    return
  }
}

// -----

// CHECK: func.func @fold_4d_constant
#layout3 = #tensor_ext.layout<"{ [f, c, fh, fw] -> [ct, slot] : ct = 0 and 0 <= f < 2 and 0 <= c < 1 and 0 <= fh < 2 and 0 <= fw < 2 and slot = 8 * f + c + 2 * fh + fw }">
module {
  func.func @fold_4d_constant() {
    %cst = arith.constant dense<1> : tensor<2x1x2x2xi32>
    // CHECK: %[[cst:.*]] = arith.constant dense<{{\[\[}}1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0{{\]\]}}> : tensor<1x32xi32>
    // CHECK: return
    %0 = secret.generic() {
      %1 = tensor_ext.assign_layout %cst {layout = #layout3, tensor_ext.layout = #layout3} : tensor<2x1x2x2xi32>
      secret.yield %1 : tensor<2x1x2x2xi32>
    } -> (!secret.secret<tensor<2x1x2x2xi32>> {tensor_ext.layout = #layout3})
    return
  }
}
