#ifndef LIB_DIALECT_RNS_IR_RNSTYPEINTERFACES_H_
#define LIB_DIALECT_RNS_IR_RNSTYPEINTERFACES_H_

#define GET_TYPEDEF_CLASSES
#include "lib/Dialect/RNS/IR/RNSTypeInterfaces.h.inc"

#endif  // LIB_DIALECT_RNS_IR_RNSTYPEINTERFACES_H_
