# YosysOptimizer files

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "share_files",
    srcs = glob([
        "*.v",
    ]),
)

exports_files([
    "*.v",
])
