# YosysOptimizer files

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files([
    "techmap_lut3.v",
    "techmap_lut4.v",
])
