load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

bzl_library(
    name = "copts_bzl",
    srcs = ["copts.bzl"],
)
