load("//third_party/bazel_skylib:bzl_library.bzl", "bzl_library")

package(
    default_applicable_licenses = ["//third_party/heir:license"],
    default_visibility = ["//third_party/heir:internal"],
)

bzl_library(
    name = "copts_bzl",
    srcs = ["copts.bzl"],
)
