# SelectVariableNames analysis pass
package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files(
    ["SelectVariableNames.h"],
)
