package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "Kernel",
    srcs = ["Kernel.cpp"],
    hdrs = ["Kernel.h"],
    deps = [
        "@llvm-project//mlir:IR",
    ],
)
