# common MLIR files used across multiple test directories

package(
    default_applicable_licenses = ["@heir//:license"],
)

exports_files(
    glob([
        "*.mlir",
    ]),
    visibility = ["@heir//tests/Examples:__subpackages__"],
)
