// RUN: heir-opt --polynomial-to-mod-arith --cse %s | FileCheck %s

// This follows from example 3.8 (Satriawan et al.) here:
// https://doi.org/10.1109/ACCESS.2023.3294446

#cycl = #polynomial.int_polynomial<1 + x**4>
!coeff_ty = !mod_arith.int<7681:i32>
#ring = #polynomial.ring<coefficientType=!coeff_ty, polynomialModulus=#cycl>
#root_val = #mod_arith.value<1213:!coeff_ty>
#root = #polynomial.primitive_root<value=#root_val, degree=8:i32>
!poly_ty = !polynomial.polynomial<ring=#ring>
!ntt_poly_ty = !polynomial.polynomial<ring=#ring, form=eval>

// CHECK:     func.func @lower_intt() -> [[MOD_TYPE:.*]] {
// CHECK:      %[[COEFFS:.*]] = arith.constant dense<[1, 2, 3, 4]> : [[INPUT_TYPE:.*]]
// CHECK:      %[[COEFFS_ENC:.*]] = mod_arith.encapsulate %[[COEFFS]] : [[INPUT_TYPE]] -> [[RING_MOD_TYPE:.*]]
// CHECK:      %[[COEFFS_CAST:.*]] = tensor.cast %[[COEFFS_ENC]] : [[RING_MOD_TYPE]] to [[MOD_TYPE:.*]]

// CHECK-DAG:  %[[INITIAL_VALUE:.*]] = mod_arith.reduce %[[COEFFS_CAST]] : [[MOD_TYPE]]
// CHECK-DAG:  %[[ROOTS:.*]] = arith.constant dense<[1, 1213, 4298, 5756]> : [[INT_TYPE:.*]]
// CHECK-DAG:  %[[ROOTS_ENC:.*]] = mod_arith.encapsulate %[[ROOTS]] : [[INT_TYPE]] -> [[MOD_TYPE]]

// CHECK-DAG:    %[[ZERO:.*]] = arith.constant 0 : index
// CHECK-DAG:    %[[ONE:.*]] = arith.constant 1 : index
// CHECK-DAG:    %[[TWO:.*]] = arith.constant 2 : index
// CHECK-DAG:    %[[N:.*]] = arith.constant 4 : index

// CHECK:        %[[RES:.]]:3 = scf.for %[[_:.*]] = %[[ZERO]] to %[[TWO]] step %[[ONE]]
// CHECK-SAME:     iter_args(%[[TARGET:.*]] = %[[INITIAL_VALUE]], %[[BATCH_SIZE:.*]] = %[[N]], %[[ROOT_EXP:.*]] = %[[ONE]]) -> ([[MOD_TYPE]], index, index) {
// CHECK-NEXT:     %[[INNER_UB:[^ ]*]] = arith.floordivsi %[[N]], %[[BATCH_SIZE]]
// CHECK:          %[[INNER_RES:.*]] = scf.for %[[INDEX:.*]] = %[[ZERO]] to %[[INNER_UB]] step %[[ONE]]
// CHECK-SAME:       iter_args(%[[INNER_TARGET:.*]] = %[[TARGET]]) -> ([[MOD_TYPE]]) {
// CHECK:            %[[INDEX_K:.*]] = arith.muli %[[BATCH_SIZE]], %[[INDEX]]
// CHECK:            %[[ARITH_UB:.*]] = arith.floordivsi %[[BATCH_SIZE]], %[[TWO]]
// CHECK:            %[[ARITH_RES:.*]] = scf.for %[[INDEX_J:.*]] = %[[ZERO]] to %[[ARITH_UB]] step %[[ONE]]
// CHECK-SAME:         iter_args(%[[ARITH_TARGET:.*]] = %[[INNER_TARGET]]) -> ([[MOD_TYPE]]) {

// CHECK:              %[[INDEX_A:.*]] = arith.addi %[[INDEX_J]], %[[INDEX_K]]
// CHECK:              %[[A:.*]] = tensor.extract %[[ARITH_TARGET]][%[[INDEX_A]]] : [[MOD_TYPE]]

// CHECK:              %[[INDEX_B:.*]] = arith.addi %[[INDEX_A]], %[[ARITH_UB]]
// CHECK:              %[[B:.*]] = tensor.extract %[[ARITH_TARGET]][%[[INDEX_B]]] : [[MOD_TYPE]]

// CHECK:              %[[IJ2:.*]] = arith.muli %[[TWO]], %[[INDEX_J]]
// CHECK:              %[[IJ2_1:.*]] = arith.addi %[[IJ2]], %[[ONE]]
// CHECK:              %[[ROOT_INDEX:.*]] = arith.muli %[[IJ2_1]], %[[ROOT_EXP]]
// CHECK:              %[[ROOT:.*]] = tensor.extract %[[ROOTS_ENC]][%[[ROOT_INDEX]]] : [[MOD_TYPE]]

// CHECK:              %[[GSPLUS:.*]] = mod_arith.add %[[A]], %[[B]] : [[COEFF_TYPE:!Z7681_i32]]
// CHECK:              %[[AMINUSB:.*]] = mod_arith.sub %[[A]], %[[B]] : [[COEFF_TYPE]]
// CHECK:              %[[GSMINUS:.*]] = mod_arith.mul %[[AMINUSB]], %[[ROOT]] : [[COEFF_TYPE]]

// CHECK:              %[[INSERT_PLUS:.*]] = tensor.insert %[[GSPLUS]] into %[[ARITH_TARGET]][%[[INDEX_A]]] : [[MOD_TYPE]]
// CHECK:              %[[INSERT_MINUS:.*]] = tensor.insert %[[GSMINUS]] into %[[INSERT_PLUS]][%[[INDEX_B]]] : [[MOD_TYPE]]
// CHECK:              scf.yield %[[INSERT_MINUS]] : [[MOD_TYPE]]

// CHECK:            scf.yield %[[ARITH_RES]] : [[MOD_TYPE]]

// CHECK:          %[[NEXT_BATCH_SIZE:.*]] = arith.divui %[[BATCH_SIZE]], %[[TWO]] : index
// CHECK:          %[[NEXT_ROOT_EXP:.*]] = arith.muli %[[ROOT_EXP]], %[[TWO]] : index
// CHECK:          scf.yield %[[INNER_RES]], %[[NEXT_BATCH_SIZE]], %[[NEXT_ROOT_EXP]] : [[MOD_TYPE]], index, index

// CHECK:       %[[N_INV_VEC:.*]] = arith.constant dense<5761> : [[INT_TYPE]]
// CHECK:       %[[N_INV_VEC_ENC:.*]] = mod_arith.encapsulate %[[N_INV_VEC]] : [[INT_TYPE]] -> [[MOD_TYPE]]

// CHECK:       %[[RES_INTT:.*]] = mod_arith.mul %[[RES]]#0, %[[N_INV_VEC_ENC]] : [[MOD_TYPE]]

// CHECK:      %[[REVERSE_BIT_ORDER_COEFFS:.*]] = arith.constant dense<[0, 2, 1, 3]> : tensor<4xindex>
// CHECK:      %[[OUTPUT_VEC:.*]] = tensor.empty() : [[INT_TYPE:.*]]
// CHECK:      %[[OUTPUT_ENC:.*]] = mod_arith.encapsulate %[[OUTPUT_VEC]] : [[INT_TYPE]] -> [[MOD_TYPE:.*]]
// CHECK:      %[[ORDERED_OUTPUT:.*]] = scf.for %[[IV:.*]] = %[[ZERO]] to %[[N]] step %[[ONE]] iter_args(%[[ITER:.*]] = %[[OUTPUT_ENC]]) -> ([[MOD_TYPE]]) {
// CHECK:        %[[REV_INDEX_FINAL:.*]] = tensor.extract %[[REVERSE_BIT_ORDER_COEFFS]][%[[IV]]] : tensor<4xindex>
// CHECK:        %[[VAL_FINAL:.*]] = tensor.extract %[[RES_INTT]][%[[REV_INDEX_FINAL]]] : [[MOD_TYPE]]
// CHECK:        %[[INSERTED_FINAL:.*]] = tensor.insert %[[VAL_FINAL]] into %[[ITER]][%[[IV]]] : [[MOD_TYPE]]
// CHECK:        scf.yield %[[INSERTED_FINAL]] : [[MOD_TYPE]]
// CHECK:      }

// CHECK:       return %[[ORDERED_OUTPUT]] : [[MOD_TYPE]]

func.func @lower_intt() -> !poly_ty {
  %coeffs = arith.constant dense<[1, 2, 3, 4]> : tensor<4xi32>
  %coeffs_enc = mod_arith.encapsulate %coeffs : tensor<4xi32> -> tensor<4x!coeff_ty>
  %poly = polynomial.from_tensor %coeffs_enc : tensor<4x!coeff_ty> -> !ntt_poly_ty
  %ret = polynomial.intt %poly {root=#root} : !ntt_poly_ty
  return %ret : !poly_ty
}
