// RUN: heir-opt --broadcast-swap --split-input-file %s | FileCheck %s
// This tests part of a layernorm generated by torch-mlir.

module {
  // CHECK: func @main
  func.func @main(%arg0: tensor<2x64x768xf32> {secret.secret}) -> tensor<2x64xf32> {
    %cst = arith.constant dense<7.680000e+02> : tensor<2x64xf32>
    // CHECK: linalg.reduce ins(%arg0 : tensor<2x64x768xf32>) outs(%cst : tensor<2x64xf32>) dimensions = [2]
    %reduced = linalg.reduce ins(%arg0 : tensor<2x64x768xf32>) outs(%cst : tensor<2x64xf32>) dimensions = [2]
      (%in: f32, %init: f32) {
        %11 = arith.addf %in, %init : f32
        linalg.yield %11 : f32
      }
    // CHECK NOT: linalg.broadcast ins(%reduced : tensor<2x64xf32>) outs(%1 : tensor<2x64x768xf32>) dimensions = [2]
    // CHECK: linalg.broadcast ins(%0 : tensor<2x64xf32>) outs(%1 : tensor<2x64x768xf32>) dimensions = [2]
    %0 = arith.mulf %reduced, %cst : tensor<2x64xf32>
    %1 = tensor.empty() : tensor<2x64x768xf32>
    %broadcasted = linalg.broadcast ins(%0 : tensor<2x64xf32>) outs(%1 : tensor<2x64x768xf32>) dimensions = [2]
    %2 = arith.subf %arg0, %broadcasted : tensor<2x64x768xf32>
    %3 = arith.mulf %2, %2 : tensor<2x64x768xf32>
    %reduced_2 = linalg.reduce ins(%3 : tensor<2x64x768xf32>) outs(%cst : tensor<2x64xf32>) dimensions = [2]
      (%in: f32, %init: f32) {
        %12 = arith.addf %in, %init : f32
        linalg.yield %12 : f32
      }
    %4 = arith.addf %0, %reduced_2 : tensor<2x64xf32>

    return %4 : tensor<2x64xf32>
  }
}
