#include <cstdint>
#include <ctime>
#include <iostream>
#include <memory>
#include <ostream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "lib/Target/OpenFhePke/Interpreter.h"
#include "mlir/include/mlir/IR/BuiltinOps.h"           // from @llvm-project
#include "mlir/include/mlir/IR/MLIRContext.h"          // from @llvm-project
#include "mlir/include/mlir/IR/OwningOpRef.h"          // from @llvm-project
#include "mlir/include/mlir/Parser/Parser.h"           // from @llvm-project
#include "src/core/include/lattice/hal/lat-backend.h"  // from @openfhe
#include "src/pke/include/cryptocontext-fwd.h"         // from @openfhe

// clang-format reordering
#include "tools/cpp/runfiles/runfiles.h"  // from @bazel_tools

// Copybara manages this declaration via regex
const std::string WORKSPACE_BASE = "";

const std::string kGeneratedModuleFile =
    "/google3/third_party/heir/tests/Examples/openfhe/ckks/lenet/"
    "lenet.openfhe.mlir";

namespace mlir {
namespace heir {
namespace openfhe {

using namespace lbcrypto;
using CryptoContextT = CryptoContext<DCRTPoly>;

}  // namespace openfhe
}  // namespace heir
}  // namespace mlir

using bazel::tools::cpp::runfiles::Runfiles;

int main(int argc, char* argv[]) {
  // Generated by the bazel rule
  std::string generatedModuleFile =
      WORKSPACE_BASE + "tests/Examples/openfhe/ckks/lenet/lenet_heir_opt.mlir";

  std::unique_ptr<Runfiles> runfiles(Runfiles::CreateForTest());

  // Load the MLIR module from a file
  mlir::MLIRContext context;
  mlir::heir::openfhe::initContext(context);
  mlir::OwningOpRef<mlir::ModuleOp> module = parseSourceFile<mlir::ModuleOp>(
      runfiles->Rlocation(kGeneratedModuleFile), &context);
  mlir::heir::openfhe::Interpreter interpreter(module.get());

  mlir::heir::openfhe::TypedCppValue ccInitial =
      interpreter.interpret("lenet__generate_crypto_context", {})[0];

  auto keyPair =
      std::get<mlir::heir::openfhe::CryptoContextT>(ccInitial.value)->KeyGen();
  auto publicKey = keyPair.publicKey;
  auto secretKey = keyPair.secretKey;
  std::vector<mlir::heir::openfhe::TypedCppValue> args = {
      ccInitial, mlir::heir::openfhe::TypedCppValue(secretKey)};
  mlir::heir::openfhe::TypedCppValue cc = std::move(
      interpreter.interpret("lenet__configure_crypto_context", args)[0]);

  // Run one inferences

  std::vector<float> input_vector(32 * 32, 0.0f);

  mlir::heir::openfhe::TypedCppValue arg0Enc = interpreter.interpret(
      "lenet__encrypt__arg0",
      {cc, mlir::heir::openfhe::TypedCppValue(input_vector),
       mlir::heir::openfhe::TypedCppValue(publicKey)})[0];

  std::clock_t cStart = std::clock();
  mlir::heir::openfhe::TypedCppValue outputEncrypted =
      interpreter.interpret("lenet", {cc, arg0Enc})[0];
  std::clock_t cEnd = std::clock();

  std::vector<mlir::heir::openfhe::TypedCppValue> actualVal =
      interpreter.interpret(
          "lenet__decrypt__result0",
          {cc, outputEncrypted, mlir::heir::openfhe::TypedCppValue(secretKey)});

  double timeElapsedMs = 1000.0 * (cEnd - cStart) / CLOCKS_PER_SEC;
  std::cout << "CPU time used: " << timeElapsedMs << " ms\n";

  return 0;
}
