#include <ctime>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "gtest/gtest.h"  // from @googletest
#include "lib/Target/OpenFhePke/Interpreter.h"
#include "mlir/include/mlir/IR/BuiltinOps.h"   // from @llvm-project
#include "mlir/include/mlir/IR/MLIRContext.h"  // from @llvm-project
#include "mlir/include/mlir/IR/OwningOpRef.h"  // from @llvm-project
#include "mlir/include/mlir/Parser/Parser.h"   // from @llvm-project

// prevent clang from reordering
#include "src/core/include/lattice/hal/lat-backend.h"  // from @openfhe
#include "src/pke/include/cryptocontext-fwd.h"         // from @openfhe
#include "src/pke/include/openfhe.h"                   // from @openfhe

// using namespace lbcrypto;

// Copybara manages this declaration via regex
const std::string WORKSPACE_BASE = "";

namespace mlir {
namespace heir {
namespace openfhe {

using namespace lbcrypto;
using CryptoContextT = CryptoContext<DCRTPoly>;

TEST(LenetTest, RunTest) {
  // Generated by the bazel rule
  std::string generatedModuleFile =
      WORKSPACE_BASE + "tests/Examples/openfhe/ckks/lenet/lenet_heir_opt.mlir";

  // Load the MLIR module from a file
  MLIRContext context;
  initContext(context);
  OwningOpRef<ModuleOp> module =
      parseSourceFile<ModuleOp>(generatedModuleFile, &context);
  Interpreter interpreter(module.get());

  TypedCppValue ccInitial =
      interpreter.interpret("lenet__generate_crypto_context", {})[0];

  auto keyPair = std::get<CryptoContextT>(ccInitial.value)->KeyGen();
  auto publicKey = keyPair.publicKey;
  auto secretKey = keyPair.secretKey;
  std::vector<TypedCppValue> args = {ccInitial, TypedCppValue(secretKey)};
  TypedCppValue cc = std::move(
      interpreter.interpret("lenet__configure_crypto_context", args)[0]);

  // Run one inference with zero data (32 x 32)
  std::vector<float> input_vector(32 * 32, 0.0f);

  TypedCppValue arg0Enc = interpreter.interpret(
      "lenet__encrypt__arg0",
      {cc, TypedCppValue(input_vector), TypedCppValue(publicKey)})[0];

  std::clock_t cStart = std::clock();
  TypedCppValue outputEncrypted =
      interpreter.interpret("lenet", {cc, arg0Enc})[0];
  std::clock_t cEnd = std::clock();

  std::vector<TypedCppValue> actualVal =
      interpreter.interpret("lenet__decrypt__result0",
                            {cc, outputEncrypted, TypedCppValue(secretKey)});

  double timeElapsedMs = 1000.0 * (cEnd - cStart) / CLOCKS_PER_SEC;
  std::cout << "CPU time used: " << timeElapsedMs << " ms\n";
}

}  // namespace openfhe
}  // namespace heir
}  // namespace mlir
