#ifndef THIRD_PARTY_HEIR_INCLUDE_DIALECT_POLY_IR_POLYTYPES_H_
#define THIRD_PARTY_HEIR_INCLUDE_DIALECT_POLY_IR_POLYTYPES_H_

#include "include/Dialect/Poly/IR/PolyDialect.h"

#define GET_TYPEDEF_CLASSES
#include "include/Dialect/Poly/IR/PolyTypes.h.inc"

#endif  // THIRD_PARTY_HEIR_INCLUDE_DIALECT_POLY_IR_POLYTYPES_H_
