# This build file marks the directory as a Bazel subpackage.

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files([
    "cheddar.BUILD",
    "libtommath.BUILD",
    "rmm.BUILD",
])
