package linear_transform

import (
	"fmt"
	"github.com/tuneinsight/lattigo/v6/circuits/ckks/lintrans"
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/ring"
	"github.com/tuneinsight/lattigo/v6/schemes/ckks"
	"math"
	"testing"
)

func TestLinearTransform(t *testing.T) {
	// This test is a bit weird because we're skipping most of the pipeline
	// to just test the emitter for linear_transform which is needed in the
	// context of comparisons with the orion compiler. This requires us to
	// manually set up the crypto parameters and encode/encrypt stuff.

	// Input vector of all 1s
	num_slots := 4096
	input_clear := make([]float64, num_slots)
	for i := range input_clear {
		input_clear[i] = 1.0
	}

	// Matrix of weights (1, 2, 3, ...)
	rows := 2
	cols := num_slots
	// Matrix is flattened 2 x num_slots
	matrix := make([]float64, rows*cols)
	row_sums := make([]float64, rows)
	value := 0.0
	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			matrix[r*num_slots+c] = float64(value)
			row_sums[r] += value
			value += 1
		}
	}

	expected_clear := make([]float64, num_slots)
	for i := range expected_clear {
		expected_clear[i] = row_sums[i%2]
	}

	// These parameters should match linear_transform.mlir, though due to
	// the weird nature of this test, this is the source of truth for what
	// is used, not the mlir file.
	param, err := ckks.NewParametersFromLiteral(ckks.ParametersLiteral{
		LogN:            13,
		Q:               []uint64{536903681, 67043329, 66994177, 67239937, 66961409, 66813953},
		P:               []uint64{536870909, 536870879},
		LogDefaultScale: 26,
	})
	if err != nil {
		panic(err)
	}

	encoder := ckks.NewEncoder(param)
	kgen := rlwe.NewKeyGenerator(param)
	sk, pk := kgen.GenKeyPairNew()
	encryptor := rlwe.NewEncryptor(param, pk)
	decryptor := rlwe.NewDecryptor(param, sk)
	evaluator := ckks.NewEvaluator(param, nil)

	// This is copied from the generated code so we can get access to the
	// Lattigo-produced Galois key set to generate... ideally this is moved
	// to a shared client helper generated by HEIR, but the client
	// interface generation is before lowering to scheme, and Orion enters
	// post-lowering-to-scheme. For this test it's OK and, if nothing else,
	// a good reference.
	ct1_diags := make(lintrans.Diagonals[float64])
	for i := 0; i < 2; i++ {
		ct1_diags[i] = matrix[i*num_slots : (i+1)*num_slots]
	}
	ct1_params := lintrans.Parameters{
		DiagonalsIndexList:        ct1_diags.DiagonalsIndexList(),
		LevelQ:                    5,
		LevelP:                    evaluator.GetRLWEParameters().MaxLevelP(),
		Scale:                     rlwe.NewScale(evaluator.GetRLWEParameters().Q()[5]),
		LogDimensions:             ring.Dimensions{Rows: 1, Cols: 12}, // 2x4096
		LogBabyStepGiantStepRatio: 2,
	}
	ct1_lt := lintrans.NewTransformation(evaluator.GetRLWEParameters(), ct1_params)
	galEls := ct1_lt.GaloisElements(param)
	evk := rlwe.NewMemEvaluationKeySet(nil, kgen.GenGaloisKeysNew(galEls, sk)...)
	evaluator = ckks.NewEvaluator(param, evk)

	pt := ckks.NewPlaintext(param, param.MaxLevel())
	pt.Scale = param.NewScale(math.Pow(2, 26)) // logDefaultScale = 26
	encoder.Encode(input_clear, pt)
	ct_input, err25 := encryptor.EncryptNew(pt)
	if err25 != nil {
		panic(err25)
	}

	result_ct := linear_transform(evaluator, param, encoder, ct_input, matrix)
	result_pt := decryptor.DecryptNew(result_ct)
	result_float64 := make([]float64, 4096)
	encoder.Decode(result_pt, result_float64)

	// 9. Verify Results
	// CKKS is approximate, so we check against a small epsilon tolerance.
	epsilon := 1e-4

	// Depending on how linear_transform packs data, you might only care about the first 'rows' indices,
	// but based on your expected_clear logic, we check the whole buffer.
	for i := 0; i < num_slots; i++ {
		diff := math.Abs(result_float64[i] - expected_clear[i])
		if diff > epsilon {
			t.Errorf("Mismatch at index %d: got %f, expected %f (diff: %e)",
				i, result_float64[i], expected_clear[i], diff)

			// Fail fast to avoid spamming 4096 errors
			if i > 10 {
				t.Fatal("Too many errors, stopping verification.")
			}
		}
	}

	fmt.Printf("Test Passed! First element: %f\n", result_float64[0])

}
