package(default_applicable_licenses = ["@heir//:license"])

cc_library(
    name = "memrefCopy",
    srcs = [
        "memrefCopy.cpp",
    ],
    visibility = ["@heir//tests/Examples/plaintext:__subpackages__"],
)
