// RUN: heir-opt --reduction-canonicalizations --split-input-file %s | FileCheck %s
// This tests a dot product generated by torch-mlir.

#map = affine_map<(d0) -> (d0)>
#map1 = affine_map<(d0) -> ()>
module {
  // CHECK: func @main
  func.func @main(%arg0: tensor<8xf32> {secret.secret}, %arg1: tensor<8xf32> {secret.secret}) -> tensor<f32> {
    // CHECK-NOT: linalg.generic
    // CHECK: linalg.reduce
    %cst = arith.constant dense<0.000000e+00> : tensor<f32>
    %0 = arith.mulf %arg0, %arg1 : tensor<8xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["reduction"]} ins(%0 : tensor<8xf32>) outs(%cst : tensor<f32>) {
    ^bb0(%in: f32, %out: f32):
      %2 = arith.addf %in, %out : f32
      linalg.yield %2 : f32
    } -> tensor<f32>
    return %1 : tensor<f32>
  }
}
