// RUN: heir-opt --reduction-canonicalizations --split-input-file %s | FileCheck %s
// This tests another reduction generated by torch-mlir.

#map = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map1 = affine_map<(d0, d1, d2) -> (d0, d1)>
module {
  // CHECK: func @main
  func.func @main(%arg0: tensor<2x64x768xf32> {secret.secret}) -> tensor<2x64x1xf32> {
    %cst = arith.constant dense<0.000000e+00> : tensor<2x64xf32>
    // CHECK-NOT: linalg.generic
    // CHECK: linalg.reduce ins(%arg0 : tensor<2x64x768xf32>) outs(%cst : tensor<2x64xf32>) dimensions = [2]
    %0 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "parallel", "reduction"]} ins(%arg0 : tensor<2x64x768xf32>) outs(%cst : tensor<2x64xf32>) {
    ^bb0(%in: f32, %out: f32):
      %1 = arith.addf %in, %out : f32
      linalg.yield %1 : f32
    } -> tensor<2x64xf32>
    %expanded = tensor.expand_shape %0 [[0], [1, 2]] output_shape [2, 64, 1] : tensor<2x64xf32> into tensor<2x64x1xf32>
    return %expanded : tensor<2x64x1xf32>
  }
}
