# common MLIR files used across multiple test directories

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files(
    glob([
        "*.mlir",
    ]),
    visibility = ["//visibility:public"],
)
