# common MLIR files used across multiple test directories

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "common",
    srcs = glob([
        "*.mlir",
    ]),
)
