# Lattigo BFV debug handler

package(
    default_applicable_licenses = ["@heir//:license"],
)

exports_files(
    glob([
        "*.go",
    ]),
    visibility = ["@heir//tests/Examples/lattigo:__subpackages__"],
)
