# Lattigo BFV debug handler

package(
    default_applicable_licenses = ["@heir//:license"],
)

# @unused
glaze_ignore = [
    "bfv_debug.go",
]

exports_files(
    glob([
        "*.go",
    ]),
    visibility = ["@heir//tests/Examples/lattigo:__subpackages__"],
)
