load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "CleartextResource",
    hdrs = ["CleartextResource.h"],
    strip_include_prefix = "/include",
)
