#include <string>
#include <utility>
#include <vector>

#include "gtest/gtest.h"  // from @googletest
#include "lib/Target/OpenFhePke/Interpreter.h"
#include "mlir/include/mlir/IR/BuiltinOps.h"   // from @llvm-project
#include "mlir/include/mlir/IR/MLIRContext.h"  // from @llvm-project
#include "mlir/include/mlir/IR/OwningOpRef.h"  // from @llvm-project
#include "mlir/include/mlir/Parser/Parser.h"   // from @llvm-project
#include "mlir/include/mlir/Support/LLVM.h"    // from @llvm-project
#include "src/pke/include/openfhe.h"           // from @openfhe

namespace mlir {
namespace heir {
namespace openfhe {

using namespace lbcrypto;
using CryptoContextT = CryptoContext<DCRTPoly>;

// Copybara manages this declaration via regex
const std::string WORKSPACE_BASE = "";

TEST(MatmulInterpreterTest, RunTest) {
  // Generated by the bazel rule
  std::string generatedModuleFile =
      WORKSPACE_BASE +
      "tests/Examples/openfhe/ckks/conv_diagonal/module.openfhe.mlir";

  // Load the MLIR module from a file
  MLIRContext context;
  initContext(context);
  OwningOpRef<ModuleOp> module =
      parseSourceFile<ModuleOp>(generatedModuleFile, &context);
  Interpreter interpreter(module.get());

  TypedCppValue ccInitial =
      interpreter.interpret("conv__generate_crypto_context", {})[0];

  auto keyPair = std::get<CryptoContextT>(ccInitial.value)->KeyGen();
  auto publicKey = keyPair.publicKey;
  auto secretKey = keyPair.secretKey;
  std::vector<TypedCppValue> args = {ccInitial, TypedCppValue(secretKey)};
  TypedCppValue cc = std::move(
      interpreter.interpret("conv__configure_crypto_context", args)[0]);

  // tensor<1x1x32x32xf32>
  std::vector<float> arg0Vals(32 * 32, 0.1f);

  TypedCppValue arg0Enc = interpreter.interpret(
      "conv__encrypt__arg0",
      {cc, TypedCppValue(arg0Vals), TypedCppValue(publicKey)})[0];

  TypedCppValue outputEncrypted =
      interpreter.interpret("conv", {cc, arg0Enc})[0];

#ifdef OPENFHE_ENABLE_TIMING
  interpreter.printTimingResults();
#endif
}

}  // namespace openfhe
}  // namespace heir
}  // namespace mlir
