#include <string>
#include <utility>
#include <vector>

#include "gtest/gtest.h"  // from @googletest
#include "lib/Target/OpenFhePke/Interpreter.h"
#include "mlir/include/mlir/IR/BuiltinOps.h"           // from @llvm-project
#include "mlir/include/mlir/IR/MLIRContext.h"          // from @llvm-project
#include "mlir/include/mlir/IR/OwningOpRef.h"          // from @llvm-project
#include "mlir/include/mlir/Parser/Parser.h"           // from @llvm-project
#include "mlir/include/mlir/Support/LLVM.h"            // from @llvm-project
#include "src/core/include/lattice/hal/lat-backend.h"  // from @openfhe
#include "src/pke/include/ciphertext-fwd.h"            // from @openfhe
#include "src/pke/include/cryptocontext-fwd.h"         // from @openfhe
#include "src/pke/include/encoding/plaintext-fwd.h"    // from @openfhe

namespace mlir {
namespace heir {
namespace openfhe {

using namespace lbcrypto;
using CryptoContextT = CryptoContext<DCRTPoly>;

// Copybara manages this declaration via regex
const std::string WORKSPACE_BASE = "";

TEST(ParallelizationInterpreterTest, RunTest) {
  // Generated by the bazel rule
  std::string generatedModuleFile =
      WORKSPACE_BASE +
      "tests/Examples/openfhe/ckks/parallelization/module.openfhe.mlir";

  // Load the MLIR module from a file
  MLIRContext context;
  initContext(context);
  OwningOpRef<ModuleOp> module =
      parseSourceFile<ModuleOp>(generatedModuleFile, &context);
  Interpreter interpreter(module.get());

  TypedCppValue ccInitial =
      interpreter.interpret("rotations__generate_crypto_context", {})[0];

  auto keyPair = std::get<CryptoContextT>(ccInitial.value)->KeyGen();
  auto publicKey = keyPair.publicKey;
  auto secretKey = keyPair.secretKey;
  std::vector<TypedCppValue> args = {ccInitial, TypedCppValue(secretKey)};
  TypedCppValue cc = std::move(
      interpreter.interpret("rotations__configure_crypto_context", args)[0]);

  std::vector<double> arg0Vals(1024, 1.0);
  CryptoContextT cryptoContext = std::get<CryptoContextT>(cc.value);
  lbcrypto::Plaintext ptxt =
      cryptoContext->MakeCKKSPackedPlaintext(arg0Vals, 1);
  ptxt->SetLength(1024);
  Ciphertext<lbcrypto::DCRTPoly> arg0Enc =
      cryptoContext->Encrypt(keyPair.publicKey, ptxt);
  std::vector<CiphertextT> arg0Vec = {arg0Enc};

  TypedCppValue outputEncrypted =
      interpreter.interpret("rotations", {cc, TypedCppValue(arg0Vec)})[0];
}

}  // namespace openfhe
}  // namespace heir
}  // namespace mlir
