// WARNING: this file is autogenerated. Do not edit manually, instead see
// scripts/generate_static_roots.py

#ifndef INCLUDE_DIALECT_POLYNOMIAL_IR_STATICROOTS_H_
#define INCLUDE_DIALECT_POLYNOMIAL_IR_STATICROOTS_H_

#include <optional>

#include "llvm/include/llvm/ADT/APInt.h"     // from @llvm-project
#include "llvm/include/llvm/ADT/DenseMap.h"  // from @llvm-project

namespace roots {

llvm::DenseMap<std::pair<unsigned, unsigned>, unsigned> STATIC_64BIT_ROOTS({
    {{12289, 256}, 3},
    {{12289, 512}, 1321},
    {{12289, 1024}, 7},
    {{8380417, 256}, 1239911},
    {{8380417, 512}, 2217225},
    {{8380417, 1024}, 2034135},
});

llvm::DenseMap<std::pair<unsigned, unsigned>, unsigned> STATIC_32BIT_ROOTS({
    {{12289, 256}, 3},
    {{12289, 512}, 1321},
    {{12289, 1024}, 7},
    {{8380417, 256}, 1239911},
    {{8380417, 512}, 2217225},
    {{8380417, 1024}, 2034135},
});

std::optional<llvm::APInt> find64BitRoot(const llvm::APInt& cMod,
                                         unsigned degree, unsigned bitWidth) {
  std::optional<llvm::APInt> root = std::nullopt;
  // We currently only precompute 64 bit and 32 bit values so we can skip
  // greater than that to ensure getZExtValue does not throw an error
  if (cMod.getBitWidth() <= 64) {
    auto rootIt = STATIC_64BIT_ROOTS.find({cMod.getZExtValue(), degree});
    if (rootIt != STATIC_64BIT_ROOTS.end())
      root = llvm::APInt(bitWidth, rootIt->second);
  }
  return root;
}

std::optional<llvm::APInt> find32BitRoot(const llvm::APInt& cMod,
                                         unsigned degree, unsigned bitWidth) {
  std::optional<llvm::APInt> root = std::nullopt;
  // We currently only precompute 64 bit and 32 bit values so we can skip
  // greater than that to ensure getZExtValue does not throw an error
  if (cMod.getBitWidth() <= 32) {
    auto rootIt = STATIC_32BIT_ROOTS.find({cMod.getZExtValue(), degree});
    if (rootIt != STATIC_32BIT_ROOTS.end())
      root = llvm::APInt(bitWidth, rootIt->second);
  }
  return root;
}

}  // namespace roots

#endif  // INCLUDE_DIALECT_POLYNOMIAL_IR_STATICROOTS_H_
