name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  create-release:
    runs-on:
      labels: ubuntu-24.04-16core
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          ./.github/install_clang_version.sh 19

      - name: "Run `bazel build`"
        run: |
          bazel build -c opt //tools:all

      - name: Ensure binaries can run
        shell: bash
        run: |
            bazel-bin/tools/heir-opt --help
            bazel-bin/tools/heir-translate --help
            bazel-bin/tools/heir-lsp --help
            [ -f bazel-bin/external/abc+/abc_bin ]

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          tag_name: v${{ steps.date.outputs.date }}
          generate_release_notes: true
          files: |
            bazel-bin/tools/heir-opt
            bazel-bin/tools/heir-translate
            bazel-bin/tools/heir-lsp
            bazel-bin/external/abc+/abc_bin
            lib/Transforms/YosysOptimizer/yosys/techmap.v
