name: Torch-MLIR Coverage

on:
  schedule:
    # On the 3rd and the 17th, to avoid race conditions with monthly scheduled
    # releases (on the 1st of the month)
    - cron: "0 0 3,17 * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --pre torch-mlir torchvision \
            --extra-index-url https://download.pytorch.org/whl/nightly/cpu \
            -f https://github.com/llvm/torch-mlir-release/releases/expanded_assets/dev-wheels

      - name: Build heir-opt
        run: |
          bazel build -c opt //tools:heir-opt

      - name: Run coverage tests
        run: |
          python scripts/torch_ci/entrypoint.py | tee coverage_table.md

      - name: Upload failure logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: failure-logs
          path: scripts/torch_ci/failure_logs/

      - name: Find Coverage Comment
        id: fc
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
        with:
          issue-number: 2923
          body-includes: '<!-- TORCH_COVERAGE_TABLE -->'

      - name: Create or Update Coverage Comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: 2923
          body-path: coverage_table.md
          edit-mode: replace
